
        //Display functions 
         function display(){
           document.querySelector("#display-message").innerHTML="Hey friend, it's been ages since we last connected, and i wanted to share something that's been on my heart. I've been thinking about God's love and how it's changed my life. His beautiful presence, His loving kindness, and His amazing grace... it's all so overwhelming! can't wait to share more about my journey with Him. Trust me, He's the best thing that's ever happened to me! Take care, and know that you're loved deeply by Him.... blessings!"
         } 